print("Here we are in the 23rd day of the ultimate python course.")
print("Here we are going to learn about the most frequently used python methods")
# s = input("Enter your String: ")
s = "denMusa"
print("Real string:",s)
print(s.capitalize())
print(s.count("a"))
print(s.endswith("OK"))
print(s.isalnum())
print(s.replace("a","e"))
print(s.removeprefix("Mr."))
print(s.encode())
print(s.casefold())
print(s.center(2))
print(s.format())
print(s.index("den"))
print(s.rpartition("@"))