print("Here we are going to learn about the list methods")
list  =["Tasmir Khan",1,2,3,4,5,6,7,8,9]
list1 = list.copy()
list1.remove("Tasmir Khan")
# list1.remove("Java")
print(list)
print(list.reverse())
print(list)
print(list.append("Java"))
print(list)
# print(list.clear())
# print(list)
print(list.count(3))
print(list.remove(6))
print(list)
print(list.insert(3,99))
print(list)
print(list.index(2))
print(list1.sort())
print(list1)
list1.extend(list)
print(list1)